// AUTO-GENERATED from the animated-emoji manifest via Python unicodedata.
// Maps each animated emoji id (Unicode codepoint hex) to a display name and a
// category so the picker can group and search them. Items missing here still
// work, just uncategorised. See the v1.1.15 commit for the generator.
export type AnimatedEmojiMeta = { n: string; c: string };
export const ANIMATED_EMOJI_META: Record<string, AnimatedEmojiMeta> = {
  "1f0cf": { n: "Playing Card Black Joker", c: "Travel & places" },
  "1f198": { n: "Squared Sos", c: "Symbols" },
  "1f30f": { n: "Earth Globe Asia-Australia", c: "Hands & people" },
  "1f315": { n: "Full Moon Symbol", c: "Animals & nature" },
  "1f31f": { n: "Glowing Star", c: "Animals & nature" },
  "1f321-fe0f": { n: "Thermometer", c: "Animals & nature" },
  "1f324-fe0f": { n: "White Sun With Small Cloud", c: "Animals & nature" },
  "1f325-fe0f": { n: "White Sun Behind Cloud", c: "Animals & nature" },
  "1f326-fe0f": { n: "White Sun Behind Cloud With Rain", c: "Animals & nature" },
  "1f327-fe0f": { n: "Cloud With Rain", c: "Animals & nature" },
  "1f32a-fe0f": { n: "Cloud With Tornado", c: "Animals & nature" },
  "1f32c-fe0f": { n: "Wind Blowing Face", c: "Animals & nature" },
  "1f32d": { n: "Hot Dog", c: "Animals & nature" },
  "1f32e": { n: "Taco", c: "Food & drink" },
  "1f32f": { n: "Burrito", c: "Food & drink" },
  "1f330": { n: "Chestnut", c: "Animals & nature" },
  "1f331": { n: "Seedling", c: "Animals & nature" },
  "1f332": { n: "Evergreen Tree", c: "Animals & nature" },
  "1f333": { n: "Deciduous Tree", c: "Animals & nature" },
  "1f335": { n: "Cactus", c: "Animals & nature" },
  "1f336-fe0f": { n: "Hot Pepper", c: "Food & drink" },
  "1f338": { n: "Cherry Blossom", c: "Animals & nature" },
  "1f339": { n: "Rose", c: "Animals & nature" },
  "1f33b": { n: "Sunflower", c: "Animals & nature" },
  "1f33c": { n: "Blossom", c: "Animals & nature" },
  "1f33d": { n: "Ear Of Maize", c: "Hands & people" },
  "1f33e": { n: "Ear Of Rice", c: "Hands & people" },
  "1f33f": { n: "Herb", c: "Animals & nature" },
  "1f341": { n: "Maple Leaf", c: "Animals & nature" },
  "1f342": { n: "Fallen Leaf", c: "Animals & nature" },
  "1f344": { n: "Mushroom", c: "Animals & nature" },
  "1f345": { n: "Tomato", c: "Food & drink" },
  "1f346": { n: "Aubergine", c: "Symbols" },
  "1f348": { n: "Melon", c: "Food & drink" },
  "1f349": { n: "Watermelon", c: "Food & drink" },
  "1f34b": { n: "Lemon", c: "Food & drink" },
  "1f34d": { n: "Pineapple", c: "Food & drink" },
  "1f34e": { n: "Red Apple", c: "Food & drink" },
  "1f34f": { n: "Green Apple", c: "Food & drink" },
  "1f350": { n: "Pear", c: "Hands & people" },
  "1f351": { n: "Peach", c: "Food & drink" },
  "1f353": { n: "Strawberry", c: "Food & drink" },
  "1f354": { n: "Hamburger", c: "Food & drink" },
  "1f355": { n: "Slice Of Pizza", c: "Food & drink" },
  "1f356": { n: "Meat On Bone", c: "Hands & people" },
  "1f357": { n: "Poultry Leg", c: "Hands & people" },
  "1f359": { n: "Rice Ball", c: "Food & drink" },
  "1f35b": { n: "Curry And Rice", c: "Food & drink" },
  "1f35e": { n: "Bread", c: "Food & drink" },
  "1f361": { n: "Dango", c: "Food & drink" },
  "1f364": { n: "Fried Shrimp", c: "Animals & nature" },
  "1f366": { n: "Soft Ice Cream", c: "Food & drink" },
  "1f369": { n: "Doughnut", c: "Food & drink" },
  "1f36a": { n: "Cookie", c: "Food & drink" },
  "1f36b": { n: "Chocolate Bar", c: "Food & drink" },
  "1f36d": { n: "Lollipop", c: "Food & drink" },
  "1f36e": { n: "Custard", c: "Animals & nature" },
  "1f370": { n: "Shortcake", c: "Food & drink" },
  "1f374": { n: "Fork And Knife", c: "Food & drink" },
  "1f378": { n: "Cocktail Glass", c: "Food & drink" },
  "1f37b": { n: "Clinking Beer Mugs", c: "Animals & nature" },
  "1f37e": { n: "Bottle With Popping Cork", c: "Food & drink" },
  "1f380": { n: "Ribbon", c: "Symbols" },
  "1f381": { n: "Wrapped Present", c: "Symbols" },
  "1f382": { n: "Birthday Cake", c: "Food & drink" },
  "1f384": { n: "Christmas Tree", c: "Animals & nature" },
  "1f385": { n: "Father Christmas", c: "Symbols" },
  "1f386": { n: "Fireworks", c: "Animals & nature" },
  "1f389": { n: "Party Popper", c: "Activities" },
  "1f38a": { n: "Confetti Ball", c: "Activities" },
  "1f396-fe0f": { n: "Military Medal", c: "Activities" },
  "1f399-fe0f": { n: "Studio Microphone", c: "Activities" },
  "1f3a3": { n: "Fishing Pole And Fish", c: "Animals & nature" },
  "1f3a4": { n: "Microphone", c: "Activities" },
  "1f3a5": { n: "Movie Camera", c: "Objects" },
  "1f3a9": { n: "Top Hat", c: "Objects" },
  "1f3ac": { n: "Clapper Board", c: "Hands & people" },
  "1f3ad": { n: "Performing Arts", c: "Activities" },
  "1f3b1": { n: "Billiards", c: "Symbols" },
  "1f3b3": { n: "Bowling", c: "Animals & nature" },
  "1f3b5": { n: "Musical Note", c: "Activities" },
  "1f3b6": { n: "Multiple Musical Notes", c: "Activities" },
  "1f3b9": { n: "Musical Keyboard", c: "Animals & nature" },
  "1f3bc": { n: "Musical Score", c: "Activities" },
  "1f3bd": { n: "Running Shirt With Sash", c: "Objects" },
  "1f3be": { n: "Tennis Racquet And Ball", c: "Activities" },
  "1f3bf": { n: "Ski And Ski Boot", c: "Activities" },
  "1f3c0": { n: "Basketball And Hoop", c: "Activities" },
  "1f3c2": { n: "Snowboarder", c: "Animals & nature" },
  "1f3c3": { n: "Runner", c: "Hands & people" },
  "1f3c4": { n: "Surfer", c: "Symbols" },
  "1f3c4-200d-2642-fe0f": { n: "Male Sign", c: "Symbols" },
  "1f3c5": { n: "Sports Medal", c: "Activities" },
  "1f3c6": { n: "Trophy", c: "Activities" },
  "1f3c7": { n: "Horse Racing", c: "Animals & nature" },
  "1f3c8": { n: "American Football", c: "Hands & people" },
  "1f3c9": { n: "Rugby Football", c: "Hands & people" },
  "1f3ca-200d-2642-fe0f": { n: "Male Sign", c: "Activities" },
  "1f3cb-fe0f": { n: "Weight Lifter", c: "Activities" },
  "1f3cb-fe0f-200d-2640-fe0f": { n: "Weight Lifter", c: "Activities" },
  "1f3cb-fe0f-200d-2642-fe0f": { n: "Weight Lifter", c: "Activities" },
  "1f3cc-fe0f-200d-2640-fe0f": { n: "Female Sign", c: "Activities" },
  "1f3cc-fe0f-200d-2642-fe0f": { n: "Male Sign", c: "Activities" },
  "1f3d0": { n: "Volleyball", c: "Activities" },
  "1f3d8-fe0f": { n: "House Buildings", c: "Travel & places" },
  "1f3d9-fe0f": { n: "Cityscape", c: "Symbols" },
  "1f3dd-fe0f": { n: "Desert Island", c: "Travel & places" },
  "1f3e1": { n: "House With Garden", c: "Travel & places" },
  "1f3e4": { n: "European Post Office", c: "Travel & places" },
  "1f3e7": { n: "Automated Teller Machine", c: "Food & drink" },
  "1f3eb": { n: "School", c: "Travel & places" },
  "1f3ef": { n: "Japanese Castle", c: "Travel & places" },
  "1f3f5-fe0f": { n: "Rosette", c: "Animals & nature" },
  "1f3fa": { n: "Amphora", c: "Symbols" },
  "1f400": { n: "Rat", c: "Animals & nature" },
  "1f401": { n: "Mouse", c: "Animals & nature" },
  "1f402": { n: "Ox", c: "Animals & nature" },
  "1f403": { n: "Water Buffalo", c: "Animals & nature" },
  "1f404": { n: "Cow", c: "Animals & nature" },
  "1f406": { n: "Leopard", c: "Symbols" },
  "1f407": { n: "Rabbit", c: "Animals & nature" },
  "1f408": { n: "Cat", c: "Animals & nature" },
  "1f409": { n: "Dragon", c: "Symbols" },
  "1f40a": { n: "Crocodile", c: "Animals & nature" },
  "1f40b": { n: "Whale", c: "Animals & nature" },
  "1f40c": { n: "Snail", c: "Animals & nature" },
  "1f40f": { n: "Ram", c: "Symbols" },
  "1f411": { n: "Sheep", c: "Symbols" },
  "1f412": { n: "Monkey", c: "Animals & nature" },
  "1f413": { n: "Rooster", c: "Animals & nature" },
  "1f414": { n: "Chicken", c: "Animals & nature" },
  "1f415-200d-1f9ba": { n: "Safety Vest", c: "Animals & nature" },
  "1f416": { n: "Pig", c: "Animals & nature" },
  "1f417": { n: "Boar", c: "Animals & nature" },
  "1f418": { n: "Elephant", c: "Animals & nature" },
  "1f419": { n: "Octopus", c: "Animals & nature" },
  "1f41a": { n: "Spiral Shell", c: "Symbols" },
  "1f41b": { n: "Bug", c: "Animals & nature" },
  "1f41c": { n: "Ant", c: "Animals & nature" },
  "1f41d": { n: "Honeybee", c: "Animals & nature" },
  "1f41e": { n: "Lady Beetle", c: "Animals & nature" },
  "1f41f": { n: "Fish", c: "Animals & nature" },
  "1f420": { n: "Tropical Fish", c: "Animals & nature" },
  "1f421": { n: "Blowfish", c: "Animals & nature" },
  "1f422": { n: "Turtle", c: "Animals & nature" },
  "1f423": { n: "Hatching Chick", c: "Animals & nature" },
  "1f424": { n: "Baby Chick", c: "Hands & people" },
  "1f425": { n: "Front-Facing Baby Chick", c: "Hands & people" },
  "1f426": { n: "Bird", c: "Animals & nature" },
  "1f427": { n: "Penguin", c: "Animals & nature" },
  "1f428": { n: "Koala", c: "Animals & nature" },
  "1f42a": { n: "Dromedary Camel", c: "Animals & nature" },
  "1f42b": { n: "Bactrian Camel", c: "Animals & nature" },
  "1f42c": { n: "Dolphin", c: "Animals & nature" },
  "1f42d": { n: "Mouse Face", c: "Smileys" },
  "1f42e": { n: "Cow Face", c: "Smileys" },
  "1f42f": { n: "Tiger Face", c: "Smileys" },
  "1f430": { n: "Rabbit Face", c: "Smileys" },
  "1f432": { n: "Dragon Face", c: "Smileys" },
  "1f433": { n: "Spouting Whale", c: "Animals & nature" },
  "1f434": { n: "Horse Face", c: "Smileys" },
  "1f437": { n: "Pig Face", c: "Smileys" },
  "1f438": { n: "Frog Face", c: "Smileys" },
  "1f439": { n: "Hamster Face", c: "Smileys" },
  "1f43a": { n: "Wolf Face", c: "Smileys" },
  "1f43b": { n: "Bear Face", c: "Smileys" },
  "1f43c": { n: "Panda Face", c: "Smileys" },
  "1f43d": { n: "Pig Nose", c: "Hands & people" },
  "1f43e": { n: "Paw Prints", c: "Animals & nature" },
  "1f43f-fe0f": { n: "Chipmunk", c: "Symbols" },
  "1f440": { n: "Eyes", c: "Hands & people" },
  "1f441-fe0f": { n: "Eye", c: "Hands & people" },
  "1f446": { n: "White Up Pointing Backhand Index", c: "Hands & people" },
  "1f447": { n: "White Down Pointing Backhand Index", c: "Hands & people" },
  "1f448": { n: "White Left Pointing Backhand Index", c: "Hands & people" },
  "1f449": { n: "White Right Pointing Backhand Index", c: "Hands & people" },
  "1f44a": { n: "Fisted Hand Sign", c: "Hands & people" },
  "1f44c": { n: "Ok Hand Sign", c: "Hands & people" },
  "1f44d": { n: "Thumbs Up Sign", c: "Hands & people" },
  "1f44e": { n: "Thumbs Down Sign", c: "Hands & people" },
  "1f44f": { n: "Clapping Hands Sign", c: "Hands & people" },
  "1f450": { n: "Open Hands Sign", c: "Hands & people" },
  "1f451": { n: "Crown", c: "Objects" },
  "1f454": { n: "Necktie", c: "Objects" },
  "1f457": { n: "Dress", c: "Objects" },
  "1f45f": { n: "Athletic Shoe", c: "Objects" },
  "1f460": { n: "High-Heeled Shoe", c: "Objects" },
  "1f463": { n: "Footprints", c: "Hands & people" },
  "1f467": { n: "Girl", c: "Hands & people" },
  "1f468": { n: "Man", c: "Hands & people" },
  "1f468-200d-1f33e": { n: "Ear Of Rice", c: "Hands & people" },
  "1f468-200d-1f373": { n: "Cooking", c: "Hands & people" },
  "1f468-200d-1f393": { n: "Graduation Cap", c: "Hands & people" },
  "1f468-200d-1f3a8": { n: "Artist Palette", c: "Hands & people" },
  "1f468-200d-1f3ed": { n: "Factory", c: "Hands & people" },
  "1f468-200d-1f466": { n: "Zero Width Joiner", c: "Hands & people" },
  "1f468-200d-1f467-200d-1f466": { n: "Zero Width Joiner", c: "Hands & people" },
  "1f468-200d-1f468-200d-1f467": { n: "Zero Width Joiner", c: "Hands & people" },
  "1f468-200d-1f468-200d-1f467-200d-1f467": { n: "Zero Width Joiner", c: "Hands & people" },
  "1f468-200d-1f469-200d-1f466-200d-1f466": { n: "Zero Width Joiner", c: "Hands & people" },
  "1f468-200d-1f4bc": { n: "Briefcase", c: "Hands & people" },
  "1f468-200d-1f527": { n: "Wrench", c: "Hands & people" },
  "1f468-200d-1f52c": { n: "Microscope", c: "Hands & people" },
  "1f468-200d-1f680": { n: "Rocket", c: "Hands & people" },
  "1f468-200d-1f692": { n: "Fire Engine", c: "Hands & people" },
  "1f468-200d-1f9af": { n: "Probing Cane", c: "Hands & people" },
  "1f468-200d-1f9bd": { n: "Manual Wheelchair", c: "Hands & people" },
  "1f468-200d-2695-fe0f": { n: "Staff Of Aesculapius", c: "Hands & people" },
  "1f468-200d-2708-fe0f": { n: "Airplane", c: "Hands & people" },
  "1f468-200d-2764-fe0f-200d-1f48b-200d-1f468": { n: "Heavy Black Heart", c: "Hearts" },
  "1f469-200d-1f33e": { n: "Ear Of Rice", c: "Hands & people" },
  "1f469-200d-1f37c": { n: "Baby Bottle", c: "Hands & people" },
  "1f469-200d-1f393": { n: "Graduation Cap", c: "Hands & people" },
  "1f469-200d-1f3eb": { n: "School", c: "Hands & people" },
  "1f469-200d-1f3ed": { n: "Factory", c: "Hands & people" },
  "1f469-200d-1f466-200d-1f466": { n: "Zero Width Joiner", c: "Hands & people" },
  "1f469-200d-1f469-200d-1f467-200d-1f466": { n: "Zero Width Joiner", c: "Hands & people" },
  "1f469-200d-1f4bc": { n: "Briefcase", c: "Hands & people" },
  "1f469-200d-1f527": { n: "Wrench", c: "Hands & people" },
  "1f469-200d-1f52c": { n: "Microscope", c: "Hands & people" },
  "1f469-200d-1f680": { n: "Rocket", c: "Hands & people" },
  "1f469-200d-1f9b3": { n: "Emoji Component White Hair", c: "Hands & people" },
  "1f469-200d-1f9bd": { n: "Manual Wheelchair", c: "Hands & people" },
  "1f469-200d-2695-fe0f": { n: "Staff Of Aesculapius", c: "Hands & people" },
  "1f469-200d-2696-fe0f": { n: "Scales", c: "Hands & people" },
  "1f469-200d-2708-fe0f": { n: "Airplane", c: "Hands & people" },
  "1f469-200d-2764-fe0f-200d-1f468": { n: "Heavy Black Heart", c: "Hearts" },
  "1f469-200d-2764-fe0f-200d-1f48b-200d-1f468": { n: "Heavy Black Heart", c: "Hearts" },
  "1f46a": { n: "Family", c: "Symbols" },
  "1f46b": { n: "Man And Woman Holding Hands", c: "Hands & people" },
  "1f46c": { n: "Two Men Holding Hands", c: "Hands & people" },
  "1f46e-200d-2640-fe0f": { n: "Police Officer", c: "Hands & people" },
  "1f46e-200d-2642-fe0f": { n: "Police Officer", c: "Hands & people" },
  "1f46f": { n: "Woman With Bunny Ears", c: "Hands & people" },
  "1f46f-200d-2642-fe0f": { n: "Woman With Bunny Ears", c: "Hands & people" },
  "1f470-200d-2640-fe0f": { n: "Bride With Veil", c: "Symbols" },
  "1f471-200d-2642-fe0f": { n: "Person With Blond Hair", c: "Hands & people" },
  "1f472": { n: "Man With Gua Pi Mao", c: "Hands & people" },
  "1f473": { n: "Man With Turban", c: "Hands & people" },
  "1f476": { n: "Baby", c: "Hands & people" },
  "1f477-200d-2640-fe0f": { n: "Construction Worker", c: "Hands & people" },
  "1f477-200d-2642-fe0f": { n: "Construction Worker", c: "Hands & people" },
  "1f47b": { n: "Ghost", c: "Symbols" },
  "1f47c": { n: "Baby Angel", c: "Hands & people" },
  "1f47f": { n: "Imp", c: "Symbols" },
  "1f480": { n: "Skull", c: "Symbols" },
  "1f481-200d-2640-fe0f": { n: "Information Desk Person", c: "Hands & people" },
  "1f481-200d-2642-fe0f": { n: "Information Desk Person", c: "Hands & people" },
  "1f482-200d-2640-fe0f": { n: "Female Sign", c: "Hands & people" },
  "1f483": { n: "Dancer", c: "Hands & people" },
  "1f486": { n: "Face Massage", c: "Smileys" },
  "1f486-200d-2642-fe0f": { n: "Face Massage", c: "Smileys" },
  "1f487": { n: "Haircut", c: "Symbols" },
  "1f487-200d-2640-fe0f": { n: "Female Sign", c: "Symbols" },
  "1f487-200d-2642-fe0f": { n: "Male Sign", c: "Symbols" },
  "1f48b": { n: "Kiss Mark", c: "Symbols" },
  "1f48c": { n: "Love Letter", c: "Symbols" },
  "1f48d": { n: "Ring", c: "Objects" },
  "1f48e": { n: "Gem Stone", c: "Objects" },
  "1f490": { n: "Bouquet", c: "Animals & nature" },
  "1f493": { n: "Beating Heart", c: "Hearts" },
  "1f494": { n: "Broken Heart", c: "Hearts" },
  "1f496": { n: "Sparkling Heart", c: "Hearts" },
  "1f497": { n: "Growing Heart", c: "Hearts" },
  "1f498": { n: "Heart With Arrow", c: "Hearts" },
  "1f499": { n: "Blue Heart", c: "Hearts" },
  "1f49a": { n: "Green Heart", c: "Hearts" },
  "1f49b": { n: "Yellow Heart", c: "Hearts" },
  "1f49c": { n: "Purple Heart", c: "Hearts" },
  "1f49d": { n: "Heart With Ribbon", c: "Hearts" },
  "1f49e": { n: "Revolving Hearts", c: "Hearts" },
  "1f49f": { n: "Heart Decoration", c: "Hearts" },
  "1f4a0": { n: "Diamond Shape With A Dot Inside", c: "Symbols" },
  "1f4a1": { n: "Electric Light Bulb", c: "Objects" },
  "1f4a2": { n: "Anger Symbol", c: "Symbols" },
  "1f4a3": { n: "Bomb", c: "Objects" },
  "1f4a4": { n: "Sleeping Symbol", c: "Symbols" },
  "1f4a6": { n: "Splashing Sweat Symbol", c: "Symbols" },
  "1f4a9": { n: "Pile Of Poo", c: "Symbols" },
  "1f4aa": { n: "Flexed Biceps", c: "Symbols" },
  "1f4ab": { n: "Dizzy Symbol", c: "Symbols" },
  "1f4af": { n: "Hundred Points Symbol", c: "Symbols" },
  "1f4b0": { n: "Money Bag", c: "Objects" },
  "1f4b2": { n: "Heavy Dollar Sign", c: "Objects" },
  "1f4b5": { n: "Banknote With Dollar Sign", c: "Activities" },
  "1f4b6": { n: "Banknote With Euro Sign", c: "Activities" },
  "1f4b7": { n: "Banknote With Pound Sign", c: "Activities" },
  "1f4b8": { n: "Money With Wings", c: "Objects" },
  "1f4bb": { n: "Personal Computer", c: "Hands & people" },
  "1f4bc": { n: "Briefcase", c: "Objects" },
  "1f4c0": { n: "Dvd", c: "Objects" },
  "1f4c1": { n: "File Folder", c: "Objects" },
  "1f4c6": { n: "Tear-Off Calendar", c: "Hands & people" },
  "1f4cb": { n: "Clipboard", c: "Animals & nature" },
  "1f4ce": { n: "Paperclip", c: "Objects" },
  "1f4d0": { n: "Triangular Ruler", c: "Objects" },
  "1f4d2": { n: "Ledger", c: "Objects" },
  "1f4d4": { n: "Notebook With Decorative Cover", c: "Hands & people" },
  "1f4d6": { n: "Open Book", c: "Objects" },
  "1f4d9": { n: "Orange Book", c: "Food & drink" },
  "1f4da": { n: "Books", c: "Objects" },
  "1f4dd": { n: "Memo", c: "Objects" },
  "1f4e0": { n: "Fax Machine", c: "Symbols" },
  "1f4e2": { n: "Public Address Loudspeaker", c: "Objects" },
  "1f4e3": { n: "Cheering Megaphone", c: "Objects" },
  "1f4e8": { n: "Incoming Envelope", c: "Objects" },
  "1f4e9": { n: "Envelope With Downwards Arrow Above", c: "Objects" },
  "1f4ef": { n: "Postal Horn", c: "Symbols" },
  "1f4f0": { n: "Newspaper", c: "Objects" },
  "1f4f1": { n: "Mobile Phone", c: "Objects" },
  "1f4f2": { n: "Mobile Phone With Rightwards Arrow At Left", c: "Objects" },
  "1f4f7": { n: "Camera", c: "Objects" },
  "1f4f8": { n: "Camera With Flash", c: "Objects" },
  "1f4f9": { n: "Video Camera", c: "Objects" },
  "1f4fa": { n: "Television", c: "Objects" },
  "1f4fc": { n: "Videocassette", c: "Objects" },
  "1f508": { n: "Speaker", c: "Objects" },
  "1f509": { n: "Speaker With One Sound Wave", c: "Objects" },
  "1f50a": { n: "Speaker With Three Sound Waves", c: "Objects" },
  "1f50c": { n: "Electric Plug", c: "Objects" },
  "1f50e": { n: "Right-Pointing Magnifying Glass", c: "Hands & people" },
  "1f511": { n: "Key", c: "Objects" },
  "1f513": { n: "Open Lock", c: "Objects" },
  "1f514": { n: "Bell", c: "Objects" },
  "1f526": { n: "Electric Torch", c: "Symbols" },
  "1f52b": { n: "Pistol", c: "Objects" },
  "1f52e": { n: "Crystal Ball", c: "Activities" },
  "1f531": { n: "Trident Emblem", c: "Symbols" },
  "1f534": { n: "Large Red Circle", c: "Symbols" },
  "1f535": { n: "Large Blue Circle", c: "Symbols" },
  "1f54a-fe0f": { n: "Dove Of Peace", c: "Symbols" },
  "1f56f-fe0f": { n: "Candle", c: "Objects" },
  "1f570-fe0f": { n: "Mantelpiece Clock", c: "Hands & people" },
  "1f575-fe0f-200d-2640-fe0f": { n: "Sleuth Or Spy", c: "Symbols" },
  "1f575-fe0f-200d-2642-fe0f": { n: "Sleuth Or Spy", c: "Symbols" },
  "1f576-fe0f": { n: "Dark Sunglasses", c: "Animals & nature" },
  "1f577-fe0f": { n: "Spider", c: "Animals & nature" },
  "1f578-fe0f": { n: "Spider Web", c: "Animals & nature" },
  "1f579-fe0f": { n: "Joystick", c: "Activities" },
  "1f57a": { n: "Man Dancing", c: "Hands & people" },
  "1f58a-fe0f": { n: "Lower Left Ballpoint Pen", c: "Activities" },
  "1f590-fe0f": { n: "Raised Hand With Fingers Splayed", c: "Hands & people" },
  "1f595": { n: "Reversed Hand With Middle Finger Extended", c: "Hands & people" },
  "1f596": { n: "Raised Hand With Part Between Middle And Ring Fingers", c: "Hands & people" },
  "1f5a4": { n: "Black Heart", c: "Hearts" },
  "1f5dc-fe0f": { n: "Compression", c: "Symbols" },
  "1f5e8-fe0f": { n: "Left Speech Bubble", c: "Symbols" },
  "1f5f3-fe0f": { n: "Ballot Box With Ballot", c: "Animals & nature" },
  "1f5fc": { n: "Tokyo Tower", c: "Travel & places" },
  "1f600": { n: "Grinning Face", c: "Smileys" },
  "1f601": { n: "Grinning Face With Smiling Eyes", c: "Smileys" },
  "1f602": { n: "Face With Tears Of Joy", c: "Smileys" },
  "1f603": { n: "Smiling Face With Open Mouth", c: "Smileys" },
  "1f604": { n: "Smiling Face With Open Mouth And Smiling Eyes", c: "Smileys" },
  "1f605": { n: "Smiling Face With Open Mouth And Cold Sweat", c: "Smileys" },
  "1f606": { n: "Smiling Face With Open Mouth And Tightly-Closed Eyes", c: "Smileys" },
  "1f607": { n: "Smiling Face With Halo", c: "Smileys" },
  "1f608": { n: "Smiling Face With Horns", c: "Smileys" },
  "1f609": { n: "Winking Face", c: "Smileys" },
  "1f60a": { n: "Smiling Face With Smiling Eyes", c: "Smileys" },
  "1f60b": { n: "Face Savouring Delicious Food", c: "Smileys" },
  "1f60c": { n: "Relieved Face", c: "Smileys" },
  "1f60d": { n: "Smiling Face With Heart-Shaped Eyes", c: "Hearts" },
  "1f60e": { n: "Smiling Face With Sunglasses", c: "Smileys" },
  "1f60f": { n: "Smirking Face", c: "Smileys" },
  "1f610": { n: "Neutral Face", c: "Smileys" },
  "1f611": { n: "Expressionless Face", c: "Smileys" },
  "1f612": { n: "Unamused Face", c: "Smileys" },
  "1f613": { n: "Face With Cold Sweat", c: "Smileys" },
  "1f614": { n: "Pensive Face", c: "Smileys" },
  "1f615": { n: "Confused Face", c: "Smileys" },
  "1f616": { n: "Confounded Face", c: "Smileys" },
  "1f617": { n: "Kissing Face", c: "Smileys" },
  "1f61b": { n: "Face With Stuck-Out Tongue", c: "Smileys" },
  "1f61c": { n: "Face With Stuck-Out Tongue And Winking Eye", c: "Smileys" },
  "1f61e": { n: "Disappointed Face", c: "Smileys" },
  "1f620": { n: "Angry Face", c: "Smileys" },
  "1f621": { n: "Pouting Face", c: "Smileys" },
  "1f622": { n: "Crying Face", c: "Smileys" },
  "1f624": { n: "Face With Look Of Triumph", c: "Smileys" },
  "1f625": { n: "Disappointed But Relieved Face", c: "Smileys" },
  "1f626": { n: "Frowning Face With Open Mouth", c: "Smileys" },
  "1f627": { n: "Anguished Face", c: "Smileys" },
  "1f628": { n: "Fearful Face", c: "Smileys" },
  "1f629": { n: "Weary Face", c: "Smileys" },
  "1f62a": { n: "Sleepy Face", c: "Smileys" },
  "1f62b": { n: "Tired Face", c: "Smileys" },
  "1f62c": { n: "Grimacing Face", c: "Smileys" },
  "1f62d": { n: "Loudly Crying Face", c: "Smileys" },
  "1f630": { n: "Face With Open Mouth And Cold Sweat", c: "Smileys" },
  "1f631": { n: "Face Screaming In Fear", c: "Smileys" },
  "1f632": { n: "Astonished Face", c: "Smileys" },
  "1f633": { n: "Flushed Face", c: "Smileys" },
  "1f637": { n: "Face With Medical Mask", c: "Smileys" },
  "1f639": { n: "Cat Face With Tears Of Joy", c: "Smileys" },
  "1f63a": { n: "Smiling Cat Face With Open Mouth", c: "Smileys" },
  "1f63b": { n: "Smiling Cat Face With Heart-Shaped Eyes", c: "Hearts" },
  "1f63c": { n: "Cat Face With Wry Smile", c: "Smileys" },
  "1f63d": { n: "Kissing Cat Face With Closed Eyes", c: "Smileys" },
  "1f63e": { n: "Pouting Cat Face", c: "Smileys" },
  "1f63f": { n: "Crying Cat Face", c: "Smileys" },
  "1f640": { n: "Weary Cat Face", c: "Smileys" },
  "1f641": { n: "Slightly Frowning Face", c: "Smileys" },
  "1f642": { n: "Slightly Smiling Face", c: "Smileys" },
  "1f643": { n: "Upside-Down Face", c: "Smileys" },
  "1f644": { n: "Face With Rolling Eyes", c: "Smileys" },
  "1f645-200d-2642-fe0f": { n: "Face With No Good Gesture", c: "Smileys" },
  "1f646-200d-2640-fe0f": { n: "Face With Ok Gesture", c: "Smileys" },
  "1f646-200d-2642-fe0f": { n: "Face With Ok Gesture", c: "Smileys" },
  "1f647-200d-2640-fe0f": { n: "Person Bowing Deeply", c: "Hands & people" },
  "1f647-200d-2642-fe0f": { n: "Person Bowing Deeply", c: "Hands & people" },
  "1f648": { n: "See-No-Evil Monkey", c: "Animals & nature" },
  "1f649": { n: "Hear-No-Evil Monkey", c: "Hands & people" },
  "1f64a": { n: "Speak-No-Evil Monkey", c: "Animals & nature" },
  "1f64b-200d-2640-fe0f": { n: "Happy Person Raising One Hand", c: "Hands & people" },
  "1f64b-200d-2642-fe0f": { n: "Happy Person Raising One Hand", c: "Hands & people" },
  "1f64c": { n: "Person Raising Both Hands In Celebration", c: "Hands & people" },
  "1f64d-200d-2640-fe0f": { n: "Person Frowning", c: "Hands & people" },
  "1f64d-200d-2642-fe0f": { n: "Person Frowning", c: "Hands & people" },
  "1f64e-200d-2640-fe0f": { n: "Person With Pouting Face", c: "Smileys" },
  "1f64e-200d-2642-fe0f": { n: "Person With Pouting Face", c: "Smileys" },
  "1f64f": { n: "Person With Folded Hands", c: "Hands & people" },
  "1f680": { n: "Rocket", c: "Travel & places" },
  "1f682": { n: "Steam Locomotive", c: "Food & drink" },
  "1f685": { n: "High-Speed Train With Bullet Nose", c: "Hands & people" },
  "1f68c": { n: "Bus", c: "Travel & places" },
  "1f690": { n: "Minibus", c: "Travel & places" },
  "1f693": { n: "Police Car", c: "Hands & people" },
  "1f696": { n: "Oncoming Taxi", c: "Travel & places" },
  "1f69c": { n: "Tractor", c: "Travel & places" },
  "1f69f": { n: "Suspension Railway", c: "Travel & places" },
  "1f6a4": { n: "Speedboat", c: "Travel & places" },
  "1f6a6": { n: "Vertical Traffic Light", c: "Travel & places" },
  "1f6b2": { n: "Bicycle", c: "Travel & places" },
  "1f6b4": { n: "Bicyclist", c: "Symbols" },
  "1f6b4-200d-2640-fe0f": { n: "Female Sign", c: "Symbols" },
  "1f6b4-200d-2642-fe0f": { n: "Bicyclist", c: "Symbols" },
  "1f6b5": { n: "Mountain Bicyclist", c: "Travel & places" },
  "1f6b5-200d-2640-fe0f": { n: "Mountain Bicyclist", c: "Travel & places" },
  "1f6b5-200d-2642-fe0f": { n: "Mountain Bicyclist", c: "Travel & places" },
  "1f6b6": { n: "Pedestrian", c: "Symbols" },
  "1f6b6-200d-2642-fe0f": { n: "Pedestrian", c: "Symbols" },
  "1f6c0": { n: "Bath", c: "Animals & nature" },
  "1f6cc": { n: "Sleeping Accommodation", c: "Symbols" },
  "1f6cd-fe0f": { n: "Shopping Bags", c: "Objects" },
  "1f6ce-fe0f": { n: "Bellhop Bell", c: "Objects" },
  "1f6cf-fe0f": { n: "Bed", c: "Objects" },
  "1f6e0-fe0f": { n: "Hammer And Wrench", c: "Objects" },
  "1f6e9-fe0f": { n: "Small Airplane", c: "Travel & places" },
  "1f6eb": { n: "Airplane Departure", c: "Activities" },
  "1f6f0-fe0f": { n: "Satellite", c: "Travel & places" },
  "1f6f5": { n: "Motor Scooter", c: "Travel & places" },
  "1f6f9": { n: "Skateboard", c: "Animals & nature" },
  "1f7e0": { n: "Large Orange Circle", c: "Food & drink" },
  "1f7e1": { n: "Large Yellow Circle", c: "Symbols" },
  "1f7e2": { n: "Large Green Circle", c: "Symbols" },
  "1f7e3": { n: "Large Purple Circle", c: "Symbols" },
  "1f7e4": { n: "Large Brown Circle", c: "Symbols" },
  "1f7e5": { n: "Large Red Square", c: "Symbols" },
  "1f7e7": { n: "Large Orange Square", c: "Food & drink" },
  "1f7e9": { n: "Large Green Square", c: "Symbols" },
  "1f7eb": { n: "Large Brown Square", c: "Symbols" },
  "1f90e": { n: "Brown Heart", c: "Hearts" },
  "1f910": { n: "Zipper-Mouth Face", c: "Smileys" },
  "1f911": { n: "Money-Mouth Face", c: "Smileys" },
  "1f912": { n: "Face With Thermometer", c: "Smileys" },
  "1f913": { n: "Nerd Face", c: "Smileys" },
  "1f914": { n: "Thinking Face", c: "Smileys" },
  "1f915": { n: "Face With Head-Bandage", c: "Smileys" },
  "1f916": { n: "Robot Face", c: "Smileys" },
  "1f918": { n: "Sign Of The Horns", c: "Symbols" },
  "1f919": { n: "Call Me Hand", c: "Hands & people" },
  "1f91a": { n: "Raised Back Of Hand", c: "Hands & people" },
  "1f91c": { n: "Right-Facing Fist", c: "Hands & people" },
  "1f91d": { n: "Handshake", c: "Hands & people" },
  "1f91e": { n: "Hand With Index And Middle Fingers Crossed", c: "Hands & people" },
  "1f923": { n: "Rolling On The Floor Laughing", c: "Symbols" },
  "1f925": { n: "Lying Face", c: "Smileys" },
  "1f926": { n: "Face Palm", c: "Smileys" },
  "1f926-200d-2640-fe0f": { n: "Female Sign", c: "Smileys" },
  "1f926-200d-2642-fe0f": { n: "Face Palm", c: "Smileys" },
  "1f928": { n: "Face With One Eyebrow Raised", c: "Smileys" },
  "1f929": { n: "Grinning Face With Star Eyes", c: "Smileys" },
  "1f92a": { n: "Grinning Face With One Large And One Small Eye", c: "Smileys" },
  "1f92b": { n: "Face With Finger Covering Closed Lips", c: "Smileys" },
  "1f92c": { n: "Serious Face With Symbols Covering Mouth", c: "Smileys" },
  "1f92d": { n: "Smiling Face With Smiling Eyes And Hand Covering Mouth", c: "Smileys" },
  "1f92e": { n: "Face With Open Mouth Vomiting", c: "Smileys" },
  "1f92f": { n: "Shocked Face With Exploding Head", c: "Smileys" },
  "1f932": { n: "Palms Up Together", c: "Hands & people" },
  "1f933": { n: "Selfie", c: "Symbols" },
  "1f935-200d-2642-fe0f": { n: "Man In Tuxedo", c: "Hands & people" },
  "1f937-200d-2642-fe0f": { n: "Male Sign", c: "Symbols" },
  "1f938": { n: "Person Doing Cartwheel", c: "Hands & people" },
  "1f938-200d-2640-fe0f": { n: "Person Doing Cartwheel", c: "Hands & people" },
  "1f938-200d-2642-fe0f": { n: "Person Doing Cartwheel", c: "Hands & people" },
  "1f939": { n: "Juggling", c: "Activities" },
  "1f939-200d-2640-fe0f": { n: "Female Sign", c: "Activities" },
  "1f939-200d-2642-fe0f": { n: "Male Sign", c: "Activities" },
  "1f93c": { n: "Wrestlers", c: "Symbols" },
  "1f93c-200d-2640-fe0f": { n: "Female Sign", c: "Symbols" },
  "1f93c-200d-2642-fe0f": { n: "Wrestlers", c: "Symbols" },
  "1f93d-200d-2640-fe0f": { n: "Female Sign", c: "Symbols" },
  "1f93e-200d-2640-fe0f": { n: "Female Sign", c: "Hands & people" },
  "1f93e-200d-2642-fe0f": { n: "Male Sign", c: "Hands & people" },
  "1f940": { n: "Wilted Flower", c: "Animals & nature" },
  "1f942": { n: "Clinking Glasses", c: "Food & drink" },
  "1f947": { n: "First Place Medal", c: "Activities" },
  "1f948": { n: "Second Place Medal", c: "Activities" },
  "1f949": { n: "Third Place Medal", c: "Activities" },
  "1f94b": { n: "Martial Arts Uniform", c: "Activities" },
  "1f94c": { n: "Curling Stone", c: "Activities" },
  "1f94d": { n: "Lacrosse Stick And Ball", c: "Activities" },
  "1f94e": { n: "Softball", c: "Activities" },
  "1f94f": { n: "Flying Disc", c: "Animals & nature" },
  "1f951": { n: "Avocado", c: "Food & drink" },
  "1f954": { n: "Potato", c: "Food & drink" },
  "1f955": { n: "Carrot", c: "Food & drink" },
  "1f957": { n: "Green Salad", c: "Food & drink" },
  "1f95d": { n: "Kiwifruit", c: "Food & drink" },
  "1f95e": { n: "Pancakes", c: "Food & drink" },
  "1f964": { n: "Cup With Straw", c: "Food & drink" },
  "1f965": { n: "Coconut", c: "Food & drink" },
  "1f966": { n: "Broccoli", c: "Food & drink" },
  "1f967": { n: "Pie", c: "Food & drink" },
  "1f96b": { n: "Canned Food", c: "Symbols" },
  "1f96c": { n: "Leafy Green", c: "Animals & nature" },
  "1f96d": { n: "Mango", c: "Hands & people" },
  "1f970": { n: "Smiling Face With Smiling Eyes And Three Hearts", c: "Hearts" },
  "1f971": { n: "Yawning Face", c: "Smileys" },
  "1f973": { n: "Face With Party Horn And Party Hat", c: "Smileys" },
  "1f974": { n: "Face With Uneven Eyes And Wavy Mouth", c: "Smileys" },
  "1f975": { n: "Overheated Face", c: "Smileys" },
  "1f976": { n: "Freezing Face", c: "Smileys" },
  "1f977": { n: "Ninja", c: "Symbols" },
  "1f97a": { n: "Face With Pleading Eyes", c: "Smileys" },
  "1f97d": { n: "Goggles", c: "Objects" },
  "1f97e": { n: "Hiking Boot", c: "Objects" },
  "1f980": { n: "Crab", c: "Animals & nature" },
  "1f981": { n: "Lion Face", c: "Smileys" },
  "1f982": { n: "Scorpion", c: "Animals & nature" },
  "1f983": { n: "Turkey", c: "Objects" },
  "1f984": { n: "Unicorn Face", c: "Smileys" },
  "1f985": { n: "Eagle", c: "Animals & nature" },
  "1f986": { n: "Duck", c: "Animals & nature" },
  "1f988": { n: "Shark", c: "Animals & nature" },
  "1f989": { n: "Owl", c: "Animals & nature" },
  "1f98a": { n: "Fox Face", c: "Smileys" },
  "1f98b": { n: "Butterfly", c: "Animals & nature" },
  "1f98e": { n: "Lizard", c: "Animals & nature" },
  "1f98f": { n: "Rhinoceros", c: "Animals & nature" },
  "1f990": { n: "Shrimp", c: "Animals & nature" },
  "1f991": { n: "Squid", c: "Animals & nature" },
  "1f992": { n: "Giraffe Face", c: "Smileys" },
  "1f993": { n: "Zebra Face", c: "Smileys" },
  "1f994": { n: "Hedgehog", c: "Animals & nature" },
  "1f995": { n: "Sauropod", c: "Animals & nature" },
  "1f997": { n: "Cricket", c: "Animals & nature" },
  "1f998": { n: "Kangaroo", c: "Symbols" },
  "1f999": { n: "Llama", c: "Symbols" },
  "1f99a": { n: "Peacock", c: "Animals & nature" },
  "1f99b": { n: "Hippopotamus", c: "Animals & nature" },
  "1f99c": { n: "Parrot", c: "Animals & nature" },
  "1f99f": { n: "Mosquito", c: "Animals & nature" },
  "1f9a1": { n: "Badger", c: "Animals & nature" },
  "1f9a2": { n: "Swan", c: "Animals & nature" },
  "1f9a5": { n: "Sloth", c: "Animals & nature" },
  "1f9a6": { n: "Otter", c: "Animals & nature" },
  "1f9a7": { n: "Orangutan", c: "Animals & nature" },
  "1f9a8": { n: "Skunk", c: "Animals & nature" },
  "1f9a9": { n: "Flamingo", c: "Animals & nature" },
  "1f9b5": { n: "Leg", c: "Hands & people" },
  "1f9b7": { n: "Tooth", c: "Hands & people" },
  "1f9b8-200d-2640-fe0f": { n: "Female Sign", c: "Symbols" },
  "1f9b8-200d-2642-fe0f": { n: "Superhero", c: "Symbols" },
  "1f9b9": { n: "Supervillain", c: "Symbols" },
  "1f9b9-200d-2640-fe0f": { n: "Supervillain", c: "Symbols" },
  "1f9bb": { n: "Ear With Hearing Aid", c: "Hands & people" },
  "1f9c1": { n: "Cupcake", c: "Food & drink" },
  "1f9c2": { n: "Salt Shaker", c: "Food & drink" },
  "1f9c5": { n: "Onion", c: "Food & drink" },
  "1f9ca": { n: "Ice Cube", c: "Symbols" },
  "1f9cd": { n: "Standing Person", c: "Hands & people" },
  "1f9cd-200d-2640-fe0f": { n: "Standing Person", c: "Hands & people" },
  "1f9cd-200d-2642-fe0f": { n: "Standing Person", c: "Hands & people" },
  "1f9ce": { n: "Kneeling Person", c: "Hands & people" },
  "1f9ce-200d-2642-fe0f": { n: "Kneeling Person", c: "Hands & people" },
  "1f9cf-200d-2640-fe0f": { n: "Deaf Person", c: "Hands & people" },
  "1f9cf-200d-2642-fe0f": { n: "Deaf Person", c: "Hands & people" },
  "1f9d0": { n: "Face With Monocle", c: "Smileys" },
  "1f9d1-200d-1f91d-200d-1f9d1": { n: "Handshake", c: "Hands & people" },
  "1f9d1-200d-1f9af": { n: "Probing Cane", c: "Symbols" },
  "1f9d1-200d-1f9bc": { n: "Motorized Wheelchair", c: "Objects" },
  "1f9d6": { n: "Person In Steamy Room", c: "Hands & people" },
  "1f9d6-200d-2642-fe0f": { n: "Person In Steamy Room", c: "Hands & people" },
  "1f9d7": { n: "Person Climbing", c: "Hands & people" },
  "1f9d7-200d-2640-fe0f": { n: "Person Climbing", c: "Hands & people" },
  "1f9d7-200d-2642-fe0f": { n: "Person Climbing", c: "Hands & people" },
  "1f9d8": { n: "Person In Lotus Position", c: "Hands & people" },
  "1f9d8-200d-2640-fe0f": { n: "Person In Lotus Position", c: "Hands & people" },
  "1f9d8-200d-2642-fe0f": { n: "Person In Lotus Position", c: "Hands & people" },
  "1f9d9": { n: "Mage", c: "Symbols" },
  "1f9d9-200d-2640-fe0f": { n: "Female Sign", c: "Symbols" },
  "1f9da": { n: "Fairy", c: "Symbols" },
  "1f9da-200d-2640-fe0f": { n: "Female Sign", c: "Symbols" },
  "1f9da-200d-2642-fe0f": { n: "Male Sign", c: "Symbols" },
  "1f9db": { n: "Vampire", c: "Symbols" },
  "1f9dc": { n: "Merperson", c: "Hands & people" },
  "1f9dc-200d-2640-fe0f": { n: "Female Sign", c: "Hands & people" },
  "1f9dc-200d-2642-fe0f": { n: "Merperson", c: "Hands & people" },
  "1f9dd": { n: "Elf", c: "Symbols" },
  "1f9dd-200d-2640-fe0f": { n: "Female Sign", c: "Symbols" },
  "1f9de": { n: "Genie", c: "Symbols" },
  "1f9de-200d-2640-fe0f": { n: "Female Sign", c: "Symbols" },
  "1f9de-200d-2642-fe0f": { n: "Male Sign", c: "Symbols" },
  "1f9e0": { n: "Brain", c: "Hands & people" },
  "1f9e1": { n: "Orange Heart", c: "Hearts" },
  "1f9e3": { n: "Scarf", c: "Travel & places" },
  "1f9e7": { n: "Red Gift Envelope", c: "Activities" },
  "1f9e8": { n: "Firecracker", c: "Animals & nature" },
  "1f9e9": { n: "Jigsaw Puzzle Piece", c: "Food & drink" },
  "1f9f2": { n: "Magnet", c: "Objects" },
  "1f9f3": { n: "Luggage", c: "Objects" },
  "1f9f5": { n: "Spool Of Thread", c: "Activities" },
  "1f9f7": { n: "Safety Pin", c: "Objects" },
  "1f9f8": { n: "Teddy Bear", c: "Hands & people" },
  "1f9fa": { n: "Basket", c: "Objects" },
  "1f9fd": { n: "Sponge", c: "Objects" },
  "1f9ff": { n: "Nazar Amulet", c: "Symbols" },
  "1fa71": { n: "One-Piece Swimsuit", c: "Food & drink" },
  "1fa73": { n: "Shorts", c: "Objects" },
  "1fa79": { n: "Adhesive Bandage", c: "Objects" },
  "1fa7a": { n: "Stethoscope", c: "Objects" },
  "1fa81": { n: "Kite", c: "Activities" },
  "1fa82": { n: "Parachute", c: "Travel & places" },
  "1fa84": { n: "Magic Wand", c: "Activities" },
  "1fa86": { n: "Nesting Dolls", c: "Activities" },
  "1fa90": { n: "Ringed Planet", c: "Objects" },
  "1fa93": { n: "Axe", c: "Objects" },
  "1fa95": { n: "Banjo", c: "Activities" },
  "1faa2": { n: "Knot", c: "Symbols" },
  "2328-fe0f": { n: "Keyboard", c: "Animals & nature" },
  "23f0": { n: "Alarm Clock", c: "Hands & people" },
  "2600-fe0f": { n: "Black Sun With Rays", c: "Animals & nature" },
  "2602-fe0f": { n: "Umbrella", c: "Objects" },
  "2611-fe0f": { n: "Ballot Box With Check", c: "Animals & nature" },
  "2618-fe0f": { n: "Shamrock", c: "Animals & nature" },
  "261d-fe0f": { n: "White Up Pointing Index", c: "Hands & people" },
  "2620-fe0f": { n: "Skull And Crossbones", c: "Hands & people" },
  "2622-fe0f": { n: "Radioactive Sign", c: "Objects" },
  "2623-fe0f": { n: "Biohazard Sign", c: "Symbols" },
  "2639-fe0f": { n: "White Frowning Face", c: "Smileys" },
  "2660-fe0f": { n: "Black Spade Suit", c: "Symbols" },
  "2663-fe0f": { n: "Black Club Suit", c: "Symbols" },
  "2666-fe0f": { n: "Black Diamond Suit", c: "Symbols" },
  "267b-fe0f": { n: "Black Universal Recycling Symbol", c: "Symbols" },
  "2693": { n: "Anchor", c: "Travel & places" },
  "2696-fe0f": { n: "Scales", c: "Symbols" },
  "26a0-fe0f": { n: "Warning Sign", c: "Symbols" },
  "26a1": { n: "High Voltage Sign", c: "Symbols" },
  "26ab": { n: "Medium Black Circle", c: "Symbols" },
  "26b0-fe0f": { n: "Coffin", c: "Symbols" },
  "26b1-fe0f": { n: "Funeral Urn", c: "Objects" },
  "26bd": { n: "Soccer Ball", c: "Activities" },
  "26c4": { n: "Snowman Without Snow", c: "Hands & people" },
  "26c5": { n: "Sun Behind Cloud", c: "Animals & nature" },
  "26c8-fe0f": { n: "Thunder Cloud And Rain", c: "Animals & nature" },
  "26d1-fe0f": { n: "Helmet With White Cross", c: "Symbols" },
  "26d4": { n: "No Entry", c: "Symbols" },
  "26f0-fe0f": { n: "Mountain", c: "Travel & places" },
  "26f1-fe0f": { n: "Umbrella On Ground", c: "Objects" },
  "26f7-fe0f": { n: "Skier", c: "Activities" },
  "26f8-fe0f": { n: "Ice Skate", c: "Activities" },
  "26f9-fe0f": { n: "Person With Ball", c: "Hands & people" },
  "26f9-fe0f-200d-2642-fe0f": { n: "Person With Ball", c: "Hands & people" },
  "2705": { n: "White Heavy Check Mark", c: "Symbols" },
  "2709-fe0f": { n: "Envelope", c: "Objects" },
  "270c-fe0f": { n: "Victory Hand", c: "Hands & people" },
  "270d-fe0f": { n: "Writing Hand", c: "Hands & people" },
  "270f-fe0f": { n: "Pencil", c: "Objects" },
  "2714-fe0f": { n: "Heavy Check Mark", c: "Symbols" },
  "2728": { n: "Sparkles", c: "Activities" },
  "2744-fe0f": { n: "Snowflake", c: "Animals & nature" },
  "2747-fe0f": { n: "Sparkle", c: "Symbols" },
  "274e": { n: "Negative Squared Cross Mark", c: "Symbols" },
  "2753": { n: "Black Question Mark Ornament", c: "Symbols" },
  "2757": { n: "Heavy Exclamation Mark Symbol", c: "Symbols" },
  "2763-fe0f": { n: "Heavy Heart Exclamation Mark Ornament", c: "Hearts" },
  "2764-fe0f": { n: "Heavy Black Heart", c: "Hearts" },
  "27b0": { n: "Curly Loop", c: "Symbols" },
  "2b55": { n: "Heavy Large Circle", c: "Symbols" },
};
